import manifest from "@/data/models.json";

export type Precision = "fp32" | "int8";

export interface ModelVariant {
  precision: Precision;
  /** Path under /public, e.g. "/models/coco80-n-int8.onnx". */
  file: string;
  bytes: number;
  /** mAP50-95 on this model's own val split; null until ml/eval_map.py has run. */
  mAP: number | null;
}

export interface ModelSpec {
  id: string;
  name: string;
  domain: string;
  description: string;
  /** Square network input side length the ONNX graph was exported at. */
  inputSize: number;
  classes: string[];
  variants: ModelVariant[];
  sample?: { video?: string; poster?: string; credit?: string };
  dataset?: { name: string; url: string; license: string };
  status: "ready" | "pending";
}

export interface ModelManifest {
  generatedAt: string;
  models: ModelSpec[];
}

/**
 * The manifest is generated by ml/export_onnx.py, not hand-maintained: file sizes
 * and mAP are measured values, so writing them by hand is how a portfolio ends up
 * quoting numbers that no longer match the weights it ships.
 */
export const MANIFEST = manifest as ModelManifest;

export const MODELS: ModelSpec[] = MANIFEST.models.filter((m) => m.status === "ready");

export const PENDING_MODELS: ModelSpec[] = MANIFEST.models.filter((m) => m.status === "pending");

export function getModel(id: string): ModelSpec | undefined {
  return MANIFEST.models.find((m) => m.id === id);
}

export function getVariant(model: ModelSpec, precision: Precision): ModelVariant | undefined {
  return model.variants.find((v) => v.precision === precision);
}

export const DEFAULT_MODEL_ID = MODELS[0]?.id ?? "coco80-n";
